services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./MongoDB:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: mongodb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

  api:
    container_name: python
    build: ./Backend/
    restart: always
    environment:
      MONGODB_URL: mongodb://admin:admin@mongo:27017/
      DATABASE_NAME: forum_db
      SECRET_KEY: 54b46e76a1599ef1f308e095da1069a03143b0f89ae6552dd24a678729f3b703
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    ports:
      - 8000:8000
    volumes:
      - ./Backend:/app

  app:
    container_name: nodejs
    build: ./Frontend/
    restart: always
    ports:
      - 5173:5173

  # nginx:
  #   container_name: nginx
  #   image: nginx:latest
  #   restart: always
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ./Frontend:/usr/share/nginx/html
  #     - ./NginxConf/nginx.conf:/etc/nginx/nginx.conf
